project_id = "nzwygirmuolgwwvtjexw"

[functions.send-magic-link]
verify_jwt = true

[functions.customer-portal]
verify_jwt = false

[functions.workspace-settings]
verify_jwt = true

[functions.wave-webhook]
verify_jwt = false
