(()=>{
const pages=document.getElementById('phonePages'),app=document.getElementById('app'),home=document.getElementById('home'),toastEl=document.getElementById('toast');
if(!pages||!app||!home)return;
const PROFILE_KEY='calculator-account-profile-v37';
const APPS_KEY='calculator-installed-v36';
const SETUP_PIN='1234';
const SUPABASE_URL='https://nzwygirmuolgwwvtjexw.supabase.co';
const SUPABASE_KEY='sb_publishable_cgOv1kSk43tKAO62az5EgQ_ieMN0_-c';
let sb=null,lastApps='',syncTimer=null;
const toast=m=>{if(!toastEl)return;toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1300)};
const show=el=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));el.classList.add('active')};
function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'null')}catch{return null}}
function saveProfile(p){localStorage.setItem(PROFILE_KEY,JSON.stringify(p));refreshIcon()}
function slug(name){return String(name||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'.').replace(/^\.+|\.+$/g,'').slice(0,40)||'user'}
function emailFor(name){return slug(name)+'@calculator-account.invalid'}
function shell(title){app.innerHTML='';const p=document.createElement('div');p.className='page account-page';const h=document.createElement('div');h.className='account-head';const b=document.createElement('button');b.className='account-back';b.textContent='‹ Home';b.onclick=()=>show(home);const t=document.createElement('h2');t.textContent=title;h.append(b,t);p.append(h);app.append(p);show(app);return p}
function field(label,type='text'){const w=document.createElement('label');w.className='account-field';const s=document.createElement('span');s.textContent=label;const i=document.createElement('input');i.type=type;i.autocomplete='off';w.append(s,i);return{wrap:w,input:i}}
function note(text){const n=document.createElement('div');n.className='account-note';n.textContent=text;return n}
async function ensureSupabase(){if(sb)return sb;if(!window.supabase?.createClient){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=reject;document.head.append(s)})}sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return sb}
async function pushApps(){const p=profile();if(!p?.cloud)return;try{const client=await ensureSupabase();const {data}=await client.auth.getSession();if(!data.session)return;const apps=JSON.parse(localStorage.getItem(APPS_KEY)||'[]');const order=JSON.parse(localStorage.getItem('phone-app-order')||'[]');await client.auth.updateUser({data:{calculator_name:p.name,installed_apps:apps,phone_order:order,updated_at:Date.now()}});lastApps=JSON.stringify(apps)}catch(e){console.warn('Account sync failed',e)}}
async function pullApps(){try{const client=await ensureSupabase();const {data}=await client.auth.getUser();const meta=data?.user?.user_metadata||{};if(Array.isArray(meta.installed_apps)){localStorage.setItem(APPS_KEY,JSON.stringify(meta.installed_apps));if(Array.isArray(meta.phone_order))localStorage.setItem('phone-app-order',JSON.stringify(meta.phone_order));window.CalculatorProApps?.syncHome?.();window.dispatchEvent(new CustomEvent('calculator-home-rendered'));return true}}catch(e){console.warn('Account restore failed',e)}return false}
function startSync(){clearInterval(syncTimer);lastApps=localStorage.getItem(APPS_KEY)||'[]';syncTimer=setInterval(()=>{const now=localStorage.getItem(APPS_KEY)||'[]';if(now!==lastApps){lastApps=now;pushApps()}},4000)}
async function signOut(){try{const client=await ensureSupabase();await client.auth.signOut()}catch{}localStorage.removeItem(PROFILE_KEY);clearInterval(syncTimer);refreshIcon();openAccount()}
function setupGate(after){const p=shell('Set Up Apple Account');const card=document.createElement('div');card.className='account-card';const pin=field('Setup PIN','password');pin.input.inputMode='numeric';pin.input.placeholder='1234';const go=document.createElement('button');go.className='account-primary';go.textContent='Continue';go.onclick=()=>{if(pin.input.value!==SETUP_PIN)return toast('Setup PIN is wrong');after()};card.append(pin.wrap,go);p.append(card,note('Calculator-only account setup. This is not a real Apple ID and should never use a real Apple password.'))}
function createScreen(){const p=shell('Create Calculator Account');const card=document.createElement('div');card.className='account-card';const name=field('Name');const pass=field('Account Password','password');const confirm=field('Confirm Password','password');name.input.placeholder='Sam';pass.input.placeholder='Choose a password';confirm.input.placeholder='Type it again';const create=document.createElement('button');create.className='account-primary';create.textContent='Create Account';create.onclick=async()=>{const n=name.input.value.trim(),pw=pass.input.value;if(n.length<2)return toast('Enter a name');if(pw.length<4)return toast('Use at least 4 characters');if(pw!==confirm.input.value)return toast('Passwords do not match');create.disabled=true;create.textContent='Creating…';try{const client=await ensureSupabase();let r=await client.auth.signUp({email:emailFor(n),password:pw,options:{data:{calculator_name:n,installed_apps:JSON.parse(localStorage.getItem(APPS_KEY)||'[]')}}});if(r.error){r=await client.auth.signInWithPassword({email:emailFor(n),password:pw});if(r.error)throw r.error}const cloud=!!r.data?.session;saveProfile({name:n,cloud,created:Date.now()});if(cloud){await pushApps();startSync();toast('Account created and synced')}else toast('Account created on this device');openAccount()}catch(e){console.warn(e);saveProfile({name:n,cloud:false,created:Date.now()});toast('Account saved on this device');openAccount()}finally{create.disabled=false;create.textContent='Create Account'}};card.append(name.wrap,pass.wrap,confirm.wrap,create);p.append(card,note('Your Calculator Account password is separate from your real Apple password.'))}
function signInScreen(){const p=shell('Sign In');const card=document.createElement('div');card.className='account-card';const name=field('Account Name');const pass=field('Password','password');name.input.placeholder='Sam';const login=document.createElement('button');login.className='account-primary';login.textContent='Sign In';login.onclick=async()=>{const n=name.input.value.trim(),pw=pass.input.value;if(!n||!pw)return toast('Enter the name and password');login.disabled=true;login.textContent='Signing In…';try{const client=await ensureSupabase();const r=await client.auth.signInWithPassword({email:emailFor(n),password:pw});if(r.error)throw r.error;saveProfile({name:n,cloud:true,created:Date.now()});const restored=await pullApps();startSync();toast(restored?'Apps restored':'Signed in');openAccount()}catch(e){console.warn(e);toast('Could not sign in to that Calculator Account')}finally{login.disabled=false;login.textContent='Sign In'}};card.append(name.wrap,pass.wrap,login);p.append(card,note('Signing in restores the apps saved to this Calculator profile when cloud sync is available.'))}
function openAccount(){const p=shell('Apple Account');const current=profile();if(current){const hero=document.createElement('div');hero.className='account-profile';const avatar=document.createElement('div');avatar.className='account-avatar';avatar.textContent=(current.name||'?').slice(0,1).toUpperCase();const text=document.createElement('div');const strong=document.createElement('strong');strong.textContent=current.name;const small=document.createElement('span');small.textContent=current.cloud?'Calculator Account · Sync On':'Calculator Account · This Device';text.append(strong,small);hero.append(avatar,text);p.append(hero);const card=document.createElement('div');card.className='account-card account-actions';const sync=document.createElement('button');sync.className='account-row';sync.textContent='Sync Installed Apps Now';sync.onclick=async()=>{await pushApps();toast('Apps synced')};const restore=document.createElement('button');restore.className='account-row';restore.textContent='Restore My Apps';restore.onclick=async()=>{const ok=await pullApps();toast(ok?'Apps restored':'No cloud app list found')};const out=document.createElement('button');out.className='account-row danger';out.textContent='Sign Out';out.onclick=signOut;card.append(sync,restore,out);p.append(card,note('This is a Calculator-only profile that can remember your private app setup.'))}else{const hero=document.createElement('div');hero.className='account-profile empty';hero.innerHTML='<div class="account-avatar"></div><div><strong>Set Up Apple Account</strong><span>Calculator-only profile</span></div>';p.append(hero);const card=document.createElement('div');card.className='account-card account-actions';const create=document.createElement('button');create.className='account-row';create.textContent='Create Account';create.onclick=()=>setupGate(createScreen);const sign=document.createElement('button');sign.className='account-row';sign.textContent='Sign In to Existing Account';sign.onclick=signInScreen;card.append(create,sign);p.append(card,note('Setup changes are protected by PIN 1234. Do not enter a real Apple ID password here.'))}}
function icon(){const b=document.createElement('button');b.className='phone-app calculator-account-launch';b.type='button';b.innerHTML='<span class="phone-icon account-icon"></span><span class="phone-label">Apple Account</span>';b.onclick=openAccount;return b}
function refreshIcon(){const existing=pages.querySelector('.calculator-account-launch');if(existing){const l=existing.querySelector('.phone-label');const name=profile()?.name||'Apple Account';if(l&&l.textContent!==name)l.textContent=name;return}const grids=pages.querySelectorAll('.phone-grid');const target=grids[0];if(target)target.prepend(icon())}
new MutationObserver(refreshIcon).observe(pages,{childList:true,subtree:true});window.addEventListener('calculator-home-rendered',()=>setTimeout(refreshIcon,0));refreshIcon();
(async()=>{const p=profile();if(p?.cloud){try{const client=await ensureSupabase();const {data}=await client.auth.getSession();if(data.session){startSync();await pullApps()}}catch{}}})();
window.CalculatorAccount={open:openAccount,sync:pushApps,restore:pullApps};
})();
