(()=>{
const pages=document.getElementById('phonePages'),app=document.getElementById('app'),home=document.getElementById('home'),toastEl=document.getElementById('toast');
if(!pages||!app||!home)return;
const PROFILE_KEY='calculator-account-profile-v37';
const SETUP_PIN='1234';
const SUPABASE_URL='https://nzwygirmuolgwwvtjexw.supabase.co';
const SUPABASE_KEY='sb_publishable_cgOv1kSk43tKAO62az5EgQ_ieMN0_-c';
const CLOUD_TABLE='calculator_cloud_profiles';
const SYNC_KEYS=[
 'calculator-installed-v36','phone-app-order','calculator-notes-v36','note',
 'pro-check-v36','pro-journal-v36','calculator-bible-state-v44',
 'calculator-bible-bookmarks-v44','calculator-bible-highlights-v44',
 'calculator-bible-notes-v44','clock-zones','clock-alarms','clock-last-tab',
 'phone-wallpaper-preset','calculator-codename','custom-mini-apps',
 'project-url-ninja','project-url-x','project-url-deepscope'
];
let sb=null,lastSnapshot='',syncTimer=null,syncing=false;
const toast=m=>{if(!toastEl)return;toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1600)};
const show=el=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));el.classList.add('active')};
function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'null')}catch{return null}}
function saveProfile(p){localStorage.setItem(PROFILE_KEY,JSON.stringify(p));refreshIcon()}
function slug(name){return String(name||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'.').replace(/^\.+|\.+$/g,'').slice(0,40)||'user'}
function emailFor(name){return slug(name)+'@calculator-account.invalid'}
function shell(title){app.innerHTML='';const p=document.createElement('div');p.className='page account-page';const h=document.createElement('div');h.className='account-head';const b=document.createElement('button');b.className='account-back';b.textContent='‹ Home';b.onclick=()=>show(home);const t=document.createElement('h2');t.textContent=title;h.append(b,t);p.append(h);app.append(p);show(app);return p}
function field(label,type='text'){const w=document.createElement('label');w.className='account-field';const s=document.createElement('span');s.textContent=label;const row=document.createElement('div');row.className='account-input-wrap';const i=document.createElement('input');i.type=type;i.autocomplete=type==='password'?'current-password':'username';row.append(i);if(type==='password'){const eye=document.createElement('button');eye.type='button';eye.className='account-eye';eye.setAttribute('aria-label','Show passcode');eye.textContent='Show';eye.onclick=()=>{const visible=i.type==='text';i.type=visible?'password':'text';eye.textContent=visible?'Show':'Hide';eye.setAttribute('aria-label',visible?'Show passcode':'Hide passcode')};row.append(eye)}w.append(s,row);return{wrap:w,input:i}}
function note(text){const n=document.createElement('div');n.className='account-note';n.textContent=text;return n}
function guide(items){const card=document.createElement('div');card.className='account-guide';const title=document.createElement('strong');title.textContent='How it works';const list=document.createElement('ol');items.forEach(text=>{const item=document.createElement('li');item.textContent=text;list.append(item)});card.append(title,list);return card}
function cloudData(){const data={};for(const key of SYNC_KEYS){const value=localStorage.getItem(key);if(value!==null&&value.length<=100000)data[key]=value}return data}
function snapshot(){return{version:1,updated_at:new Date().toISOString(),data:cloudData()}}
function applySnapshot(value){const data=value?.data&&typeof value.data==='object'?value.data:null;if(!data)return false;for(const key of SYNC_KEYS){const value=data[key];if(typeof value==='string'&&value.length<=100000)localStorage.setItem(key,value)}window.CalculatorProApps?.syncHome?.();window.dispatchEvent(new CustomEvent('calculator-home-rendered'));window.CalculatorPersonalize?.apply?.();return true}
function signature(){return JSON.stringify(cloudData())}
async function ensureSupabase(){if(sb)return sb;if(!window.supabase?.createClient){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=()=>reject(new Error('Cloud service could not load'));document.head.append(s)})}sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return sb}
async function session(){const client=await ensureSupabase();const {data,error}=await client.auth.getSession();if(error)throw error;if(!data.session)throw new Error('Cloud session is not active');return{client,current:data.session}}
async function pushCloud(){if(syncing)return false;syncing=true;try{const p=profile();if(!p?.cloud)return false;const {client,current}=await session(),payload=snapshot();const {error}=await client.from(CLOUD_TABLE).upsert({user_id:current.user.id,payload,updated_at:payload.updated_at},{onConflict:'user_id'});if(error)throw error;await client.auth.updateUser({data:{calculator_name:p.name,installed_apps:JSON.parse(localStorage.getItem('calculator-installed-v36')||'[]'),phone_order:JSON.parse(localStorage.getItem('phone-app-order')||'[]'),calculator_cloud_updated_at:payload.updated_at}});lastSnapshot=signature();saveProfile({...p,lastSync:payload.updated_at});return true}catch(e){console.warn('Calculator cloud sync failed',e);return false}finally{syncing=false}}
async function pullCloud(){try{const {client,current}=await session();const {data,error}=await client.from(CLOUD_TABLE).select('payload,updated_at').eq('user_id',current.user.id).maybeSingle();if(error)throw error;let restored=applySnapshot(data?.payload);if(!restored){const meta=current.user.user_metadata||{};if(Array.isArray(meta.installed_apps)){localStorage.setItem('calculator-installed-v36',JSON.stringify(meta.installed_apps));if(Array.isArray(meta.phone_order))localStorage.setItem('phone-app-order',JSON.stringify(meta.phone_order));restored=true}}if(restored){lastSnapshot=signature();const p=profile();if(p)saveProfile({...p,lastSync:data?.updated_at||new Date().toISOString()})}return restored}catch(e){console.warn('Calculator cloud restore failed',e);return false}}
function startSync(){clearInterval(syncTimer);lastSnapshot=signature();syncTimer=setInterval(async()=>{const now=signature();if(now!==lastSnapshot){const ok=await pushCloud();if(ok)lastSnapshot=now}},5000)}
async function signOut(){try{const client=await ensureSupabase();await client.auth.signOut()}catch{}localStorage.removeItem(PROFILE_KEY);clearInterval(syncTimer);refreshIcon();openAccount()}
function setupGate(after){const p=shell('Set Up Calculator Account');const form=document.createElement('form');form.className='account-card';const pin=field('Setup PIN','password');pin.input.inputMode='numeric';pin.input.placeholder='Enter the 4-digit setup PIN';const go=document.createElement('button');go.type='submit';go.className='account-primary';go.textContent='Continue';form.onsubmit=e=>{e.preventDefault();if(pin.input.value!==SETUP_PIN)return toast('Setup PIN is wrong');after()};form.append(pin.wrap,go);p.append(guide(['Enter the setup PIN.','Choose a Calculator Account name and passcode.','Your supported settings will be backed up.']),note('Use a new Calculator passcode here—never enter your Apple Account password.'))}
function createScreen(){const p=shell('Create Calculator Account');const form=document.createElement('form');form.className='account-card';const name=field('Calculator Account Name'),pass=field('Calculator Account Passcode','password'),confirm=field('Confirm Calculator Passcode','password');name.input.placeholder='Choose a name, such as Sam';pass.input.placeholder='Use at least 6 characters';confirm.input.placeholder='Type the same passcode again';const create=document.createElement('button');create.type='submit';create.className='account-primary';create.textContent='Create Account and Sync';form.onsubmit=async e=>{e.preventDefault();const n=name.input.value.trim(),pw=pass.input.value;if(n.length<2)return toast('Enter an account name');if(pw.length<6)return toast('Use at least 6 characters');if(pw!==confirm.input.value)return toast('Passcodes do not match');create.disabled=true;create.textContent='Creating…';try{const client=await ensureSupabase();let result=await client.auth.signUp({email:emailFor(n),password:pw,options:{data:{calculator_name:n}}});if(result.error&&/already|registered|exists/i.test(result.error.message||''))result=await client.auth.signInWithPassword({email:emailFor(n),password:pw});if(result.error)throw result.error;if(!result.data?.session)throw new Error('Cloud account requires server approval');saveProfile({name:n,cloud:true,created:Date.now()});const synced=await pushCloud();if(!synced)throw new Error('Initial cloud save failed');startSync();toast('Calculator Account created and this device is synced');openAccount()}catch(err){console.warn(err);toast('Account was not created. Check the name, passcode, and internet connection.')}finally{create.disabled=false;create.textContent='Create Account and Sync'}};form.append(name.wrap,pass.wrap,confirm.wrap,create);p.append(form,note('Write down this Calculator Account name and passcode. You will need both to restore another device.'))}
function signInScreen(){const p=shell('Restore Calculator Account');const form=document.createElement('form');form.className='account-card';const name=field('Calculator Account Name'),pass=field('Calculator Account Passcode','password');name.input.placeholder='Enter the name you created';pass.input.placeholder='Enter your Calculator passcode';const login=document.createElement('button');login.type='submit';login.className='account-primary';login.textContent='Sign In and Restore';form.onsubmit=async e=>{e.preventDefault();const n=name.input.value.trim(),pw=pass.input.value;if(!n||!pw)return toast('Enter your Calculator Account name and passcode');login.disabled=true;login.textContent='Restoring…';try{const client=await ensureSupabase();const result=await client.auth.signInWithPassword({email:emailFor(n),password:pw});if(result.error)throw result.error;saveProfile({name:n,cloud:true,created:Date.now()});const restored=await pullCloud();startSync();toast(restored?'Your Calculator setup was restored':'Signed in; no saved setup was found');openAccount()}catch(err){console.warn(err);toast('That Calculator Account name or passcode did not work')}finally{login.disabled=false;login.textContent='Sign In and Restore'}};form.append(name.wrap,pass.wrap,login);p.append(guide(['Enter the exact account name you created.','Enter that account’s Calculator passcode.','Tap “Sign In and Restore” to download your saved setup.']),form,note('This restores supported apps and preferences. It does not use your Apple Account.'))}
function openAccount(){const p=shell('Calculator Account');const current=profile();if(current){const hero=document.createElement('div');hero.className='account-profile';const avatar=document.createElement('div');avatar.className='account-avatar';avatar.textContent=(current.name||'?').slice(0,1).toUpperCase();const text=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('span');strong.textContent=current.name;small.textContent=current.cloud?'Calculator Account · Sync On':'Calculator Account · Not Connected';text.append(strong,small);hero.append(avatar,text);p.append(hero);const card=document.createElement('div');card.className='account-card account-actions';if(current.cloud){const sync=document.createElement('button');sync.className='account-row';sync.textContent='Sync This Device Now';sync.onclick=async()=>toast(await pushCloud()?'Calculator data synced':'Cloud sync failed');const restore=document.createElement('button');restore.className='account-row';restore.textContent='Restore Saved Setup';restore.onclick=async()=>toast(await pullCloud()?'Calculator data restored':'No cloud backup was found');card.append(sync,restore)}else{const sign=document.createElement('button');sign.className='account-row';sign.textContent='Sign In and Restore';sign.onclick=signInScreen;const connect=document.createElement('button');connect.className='account-row';connect.textContent='Create Calculator Account';connect.onclick=()=>setupGate(createScreen);card.append(sign,connect)}const out=document.createElement('button');out.className='account-row danger';out.textContent=current.cloud?'Sign Out':'Remove Local Account';out.onclick=signOut;card.append(out);p.append(card,note('Sync includes installed apps, layout, notes, Bible saves and preferences, alarms, and compatible settings. Calls, messages, photos, files, and device passcodes stay on each device. This is not end-to-end encrypted.'))}else{const hero=document.createElement('div');hero.className='account-profile empty';hero.innerHTML='<div class="account-avatar account-avatar-ca">CA</div><div><strong>Calculator Account</strong><span>Back up your setup and restore it on another device</span></div>';p.append(hero,guide(['New here? Tap “Create Calculator Account.”','Already made one? Tap “Sign In and Restore.”','Use only the Calculator Account name and passcode you created here.']));const card=document.createElement('div');card.className='account-card account-actions';const sign=document.createElement('button');sign.className='account-row';sign.textContent='Sign In and Restore';sign.onclick=signInScreen;const create=document.createElement('button');create.className='account-row';create.textContent='Create Calculator Account';create.onclick=()=>setupGate(createScreen);card.append(sign,create);p.append(card,note('This is separate from Apple. Never enter your Apple Account name or password here.'))}}
function icon(){const b=document.createElement('button');b.className='phone-app calculator-account-launch';b.type='button';b.innerHTML='<span class="phone-icon account-icon">CA</span><span class="phone-label">Account</span>';b.onclick=openAccount;return b}
function refreshIcon(){const existing=pages.querySelector('.calculator-account-launch');if(existing){const label=existing.querySelector('.phone-label');if(label&&label.textContent!=='Account')label.textContent='Account';const badge=existing.querySelector('.account-icon');if(badge&&badge.textContent!=='CA')badge.textContent='CA';return}const target=pages.querySelectorAll('.phone-grid')[0];target?.prepend(icon())}
new MutationObserver(refreshIcon).observe(pages,{childList:true,subtree:true});window.addEventListener('calculator-home-rendered',()=>setTimeout(refreshIcon,0));refreshIcon();
(async()=>{const p=profile();if(p?.cloud){try{await session();startSync()}catch{saveProfile({...p,cloud:false})}}})();
window.CalculatorAccount={open:openAccount,sync:pushCloud,restore:pullCloud,snapshot};
})();
