(()=>{
const app=document.getElementById('app'),home=document.getElementById('home'),pages=document.getElementById('phonePages'),toastEl=document.getElementById('toast');
if(!app||!home||!pages)return;
const $=s=>document.querySelector(s);
function show(el){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
function toast(m){if(!toastEl)return;toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1300)}
function shell(title){app.innerHTML='';const p=document.createElement('div');p.className='page builtin-page';const h=document.createElement('div');h.className='head';const b=document.createElement('button');b.className='back';b.textContent='‹ Home';b.onclick=()=>show(home);const t=document.createElement('h2');t.textContent=title;h.append(b,t);p.append(h);app.append(p);show(app);return p}

// IndexedDB keeps actual files/photos on this installation instead of only showing their names.
const DB='calculator-private-storage-v1';
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('files'))d.createObjectStore('files',{keyPath:'id'});if(!d.objectStoreNames.contains('photos'))d.createObjectStore('photos',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getAll(store){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function put(store,v){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(store,'readwrite').objectStore(store).put(v);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
async function del(store,id){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function size(n){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}

async function openFiles(){
 const p=shell('Files');
 const top=document.createElement('div');top.className='builtin-toolbar';
 const add=document.createElement('button');add.className='primary';add.textContent='+ Add Files';
 const input=document.createElement('input');input.type='file';input.multiple=true;input.hidden=true;add.onclick=()=>input.click();
 const subtitle=document.createElement('div');subtitle.className='muted builtin-subtitle';subtitle.textContent='Files saved here stay inside this Calculator on this device.';
 const list=document.createElement('div');list.className='builtin-file-list';top.append(add,input);p.append(top,subtitle,list);
 async function draw(){const items=(await getAll('files')).sort((a,b)=>b.time-a.time);list.innerHTML='';if(!items.length){list.innerHTML='<div class="builtin-empty"><div class="builtin-empty-icon">📁</div><strong>No files yet</strong><span>Tap Add Files to store something here.</span></div>';return}for(const x of items){const row=document.createElement('div');row.className='builtin-file-row';const icon=document.createElement('div');icon.className='builtin-file-icon';icon.textContent=x.type?.startsWith('image/')?'🖼️':x.type?.includes('pdf')?'PDF':'📄';const info=document.createElement('button');info.className='builtin-file-info';info.innerHTML=`<strong></strong><small>${size(x.size||0)} · ${new Date(x.time).toLocaleDateString()}</small>`;info.querySelector('strong').textContent=x.name;info.onclick=()=>{const u=URL.createObjectURL(x.blob);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)};const more=document.createElement('button');more.className='builtin-more';more.textContent='•••';more.onclick=async()=>{if(confirm('Delete '+x.name+'?')){await del('files',x.id);draw()}};row.append(icon,info,more);list.append(row)}}
 input.onchange=async()=>{for(const f of input.files){await put('files',{id:crypto.randomUUID(),name:f.name,type:f.type,size:f.size,time:Date.now(),blob:f})}input.value='';await draw();toast('Files saved')};
 draw().catch(()=>{list.textContent='Could not open private file storage.'});
}

async function openPhotos(){
 const p=shell('Photos');const top=document.createElement('div');top.className='builtin-toolbar';const add=document.createElement('button');add.className='primary';add.textContent='+ Add Photos';const input=document.createElement('input');input.type='file';input.accept='image/*';input.multiple=true;input.hidden=true;add.onclick=()=>input.click();top.append(add,input);const grid=document.createElement('div');grid.className='builtin-photo-grid';p.append(top,grid);
 let urls=[];async function draw(){urls.forEach(URL.revokeObjectURL);urls=[];const items=(await getAll('photos')).sort((a,b)=>b.time-a.time);grid.innerHTML='';if(!items.length){grid.innerHTML='<div class="builtin-empty photo-empty"><div class="builtin-empty-icon">🌈</div><strong>No photos yet</strong><span>Add photos from your iPhone.</span></div>';return}for(const x of items){const wrap=document.createElement('button');wrap.className='builtin-photo';const u=URL.createObjectURL(x.blob);urls.push(u);const im=document.createElement('img');im.src=u;im.alt=x.name||'Photo';wrap.append(im);wrap.onclick=()=>{const overlay=document.createElement('div');overlay.className='builtin-photo-viewer';const big=document.createElement('img');big.src=u;const close=document.createElement('button');close.textContent='Done';close.onclick=()=>overlay.remove();const trash=document.createElement('button');trash.textContent='Delete';trash.onclick=async()=>{await del('photos',x.id);overlay.remove();draw()};overlay.append(close,big,trash);document.body.append(overlay)};grid.append(wrap)}}
 input.onchange=async()=>{for(const f of input.files){await put('photos',{id:crypto.randomUUID(),name:f.name,type:f.type,size:f.size,time:Date.now(),blob:f})}input.value='';draw();toast('Photos added')};draw();
}

function openSketch(){
 const p=shell('Sketch');const tools=document.createElement('div');tools.className='sketch-tools';const clear=document.createElement('button');clear.textContent='Clear';const save=document.createElement('button');save.className='primary';save.textContent='Save to Photos';tools.append(clear,save);const wrap=document.createElement('div');wrap.className='builtin-canvas-wrap';const c=document.createElement('canvas');wrap.append(c);p.append(tools,wrap);let ctx,down=false,last=null;
 function fit(){const r=wrap.getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);c.style.width=r.width+'px';c.style.height=r.height+'px';ctx=c.getContext('2d');ctx.scale(d,d);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=4;ctx.strokeStyle='#111';ctx.fillStyle='#fff';ctx.fillRect(0,0,r.width,r.height)}requestAnimationFrame(fit);
 const pt=e=>{const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};c.addEventListener('pointerdown',e=>{down=true;last=pt(e);c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointermove',e=>{if(!down||!ctx)return;const q=pt(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(q.x,q.y);ctx.stroke();last=q});c.addEventListener('pointerup',()=>down=false);c.addEventListener('pointercancel',()=>down=false);clear.onclick=fit;save.onclick=()=>c.toBlob(async blob=>{if(!blob)return;await put('photos',{id:crypto.randomUUID(),name:'Sketch '+new Date().toLocaleString()+'.png',type:'image/png',size:blob.size,time:Date.now(),blob});toast('Saved to Photos')},'image/png');
}

function openGame(){
 const p=shell('Tic-Tac-Toe');const status=document.createElement('div');status.className='ttt-status';const board=document.createElement('div');board.className='ttt-board';const reset=document.createElement('button');reset.className='primary ttt-reset';reset.textContent='New Game';p.append(status,board,reset);let cells=Array(9).fill(''),turn='X',done=false;const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];function draw(){board.innerHTML='';cells.forEach((v,i)=>{const b=document.createElement('button');b.className='ttt-cell';b.textContent=v;b.onclick=()=>{if(done||cells[i])return;cells[i]=turn;if(wins.some(w=>w.every(j=>cells[j]===turn))){done=true;status.textContent=turn+' wins!'}else if(cells.every(Boolean)){done=true;status.textContent='Draw'}else{turn=turn==='X'?'O':'X';status.textContent=turn+"'s turn"}draw()};board.append(b)});if(!done)status.textContent=turn+"'s turn"}reset.onclick=()=>{cells=Array(9).fill('');turn='X';done=false;draw()};draw();
}

function openStore(){
 const p=shell('App Store');const intro=document.createElement('div');intro.className='muted builtin-subtitle';intro.textContent='Your connected Calculator apps.';const list=document.createElement('div');list.className='builtin-store-list';p.append(intro,list);
 const items=[['🥷','Ninja',localStorage.getItem('project-url-ninja')||''],['Y','Ninja Y','https://ninja-y-game.cwhit.chatgpt.site'],['X','X',localStorage.getItem('project-url-x')||''],['MM',"Malachi's Mowing",'https://malachis-mowing-fort-scott.cwhit.chatgpt.site'],['🎬','Brainrot Movie Maker','https://brainrot-movie-maker.cwhit.chatgpt.site'],['◉','Deep Scope',localStorage.getItem('project-url-deepscope')||'']];
 for(const [ic,name,url] of items){const row=document.createElement('div');row.className='builtin-store-row';const icon=document.createElement('div');icon.className='builtin-store-icon';icon.textContent=ic;const info=document.createElement('div');info.innerHTML='<strong></strong><small></small>';info.querySelector('strong').textContent=name;info.querySelector('small').textContent=url?'Connected':'Link not connected';const b=document.createElement('button');b.className='get';b.textContent=url?'OPEN':'SET UP';b.onclick=()=>{if(url)location.href=url;else{show(home);setTimeout(()=>{[...pages.querySelectorAll('.phone-app')].find(x=>x.querySelector('.phone-label')?.textContent===name)?.click()},0)}};row.append(icon,info,b);list.append(row)}
}

function openSecondSpace(){
 const p=shell('Second Space');const hero=document.createElement('div');hero.className='second-space-hero';hero.innerHTML='<div>◉</div><strong>Second Space</strong><span>A separate set of private tools.</span>';const grid=document.createElement('div');grid.className='second-space-grid';const choices=[['📝','Second Notes',()=>secondNotes()],['📁','Files',openFiles],['🌈','Photos',openPhotos],['✎','Sketch',openSketch]];for(const [ic,name,fn] of choices){const b=document.createElement('button');b.innerHTML=`<span>${ic}</span><strong>${name}</strong>`;b.onclick=fn;grid.append(b)}p.append(hero,grid)
}
function secondNotes(){const p=shell('Second Notes'),ta=document.createElement('textarea');ta.className='note';ta.placeholder='Write private notes for Second Space…';ta.value=localStorage.getItem('second-space-note')||'';ta.oninput=()=>localStorage.setItem('second-space-note',ta.value);p.append(ta)}

const handlers={Files:openFiles,Photos:openPhotos,Sketch:openSketch,'Tic-Tac-Toe':openGame,'App Store':openStore,'Second Space':openSecondSpace};
pages.addEventListener('click',e=>{const button=e.target.closest('.phone-app');if(!button)return;const label=button.querySelector('.phone-label')?.textContent?.trim();const fn=handlers[label];if(!fn)return;e.preventDefault();e.stopImmediatePropagation();fn()},true);
// Dock can contain App Store too.
document.getElementById('phoneDock')?.addEventListener('click',e=>{const button=e.target.closest('.phone-app');if(!button)return;const label=button.querySelector('.phone-label')?.textContent?.trim();const fn=handlers[label];if(!fn)return;e.preventDefault();e.stopImmediatePropagation();fn()},true);
})();