(()=>{
const home=document.getElementById('home'),app=document.getElementById('app');
if(!home||!app)return;
const presets={
 blue:'radial-gradient(circle at 78% 12%,#7ed3ff99 0 10%,transparent 30%),radial-gradient(circle at 10% 86%,#966dff77 0 13%,transparent 34%),linear-gradient(155deg,#092243 0%,#174f7a 46%,#241c55 100%)',
 aurora:'radial-gradient(ellipse at 18% 28%,#55f0c488 0 12%,transparent 36%),radial-gradient(ellipse at 82% 62%,#9a65ff88 0 16%,transparent 40%),linear-gradient(155deg,#061b24,#113a46 48%,#17133b)',
 ocean:'radial-gradient(circle at 72% 18%,#b6f5ff77 0 10%,transparent 32%),radial-gradient(circle at 15% 80%,#21d4a766 0 13%,transparent 36%),linear-gradient(160deg,#063b59,#0c7d93 50%,#04243f)',
 sunset:'radial-gradient(circle at 72% 18%,#ffe5a399 0 10%,transparent 34%),radial-gradient(circle at 18% 76%,#bf4aa566 0 16%,transparent 40%),linear-gradient(165deg,#34285d 0%,#ac426a 48%,#f08a50 100%)',
 forest:'radial-gradient(circle at 70% 15%,#b6e6a566 0 12%,transparent 34%),radial-gradient(circle at 10% 78%,#53ac8877 0 14%,transparent 38%),linear-gradient(160deg,#0b302a,#215b46 50%,#081c1d)',
 dark:'radial-gradient(circle at 78% 14%,#637d9b55 0 12%,transparent 34%),radial-gradient(circle at 14% 82%,#3f477c55 0 14%,transparent 38%),linear-gradient(155deg,#090c12,#1c2431 52%,#05070b)',
 moon:'linear-gradient(#0000000d,#00000020),url("./calculator/wallpaper-moon.svg")',
 mountains:'linear-gradient(#0000000d,#0000001f),url("./calculator/wallpaper-mountains.svg")'
};
function shell(){return home.querySelector('.phone-shell')}
function applyWallpaper(){const s=shell();if(!s)return;const image=localStorage.getItem('phone-wallpaper-image');const preset=localStorage.getItem('phone-wallpaper-preset')||'blue';if(image){s.style.backgroundImage=`linear-gradient(#00000018,#00000018),url(${JSON.stringify(image)})`;s.style.backgroundSize='cover';s.style.backgroundPosition='center';}else{s.style.backgroundImage=presets[preset]||presets.blue;s.style.backgroundSize='cover';s.style.backgroundPosition='center'}}
function toast(m){const t=document.getElementById('toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1200)}
function compress(file,max=1000,quality=.78){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=reject;fr.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',quality))};img.src=fr.result};fr.readAsDataURL(file)})}
function setWallpaper(src){if(src){try{localStorage.setItem('phone-wallpaper-image',src)}catch{toast('That photo is too large');return}}else localStorage.removeItem('phone-wallpaper-image');applyWallpaper();toast('Wallpaper changed')}
function presetButton(name,label,bg){const b=document.createElement('button');b.type='button';b.style.cssText=`height:92px;border-radius:17px;background:${bg};color:white;font-weight:800;text-shadow:0 1px 4px #0008`;b.textContent=label;b.onclick=()=>{localStorage.setItem('phone-wallpaper-preset',name);localStorage.removeItem('phone-wallpaper-image');applyWallpaper();toast('Wallpaper changed')};return b}
function wallpaperPanel(){const wrap=document.createElement('div');wrap.className='card personalization-card';const title=document.createElement('strong');title.textContent='Choose a Background';const sub=document.createElement('div');sub.className='muted';sub.textContent='Pick a built-in scene or use one of your photos.';const grid=document.createElement('div');grid.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:12px';grid.append(presetButton('blue','Blue Glow',presets.blue),presetButton('aurora','Aurora',presets.aurora),presetButton('ocean','Ocean',presets.ocean),presetButton('sunset','Sunset',presets.sunset),presetButton('forest','Forest',presets.forest),presetButton('dark','Midnight',presets.dark),presetButton('moon','Moon',presets.moon),presetButton('mountains','Mountains',presets.mountains));const label=document.createElement('label');label.style.cssText='display:block;margin-top:12px;background:linear-gradient(135deg,#0a84ff,#5358e8);color:white;padding:12px 14px;border-radius:13px;font-weight:800;text-align:center;box-shadow:0 8px 20px #0a66ff33';label.textContent='Choose My Photo';const inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.hidden=true;label.append(inp);inp.onchange=async()=>{const f=inp.files&&inp.files[0];if(!f)return;try{setWallpaper(await compress(f))}catch{toast('Could not use that photo')}inp.value=''};const clear=document.createElement('button');clear.className='reset';clear.textContent='Use Built-in Background';clear.onclick=()=>{localStorage.removeItem('phone-wallpaper-image');applyWallpaper();toast('Built-in background restored')};wrap.append(title,sub,grid,label,clear);return wrap}
function enhanceSettings(){const h=app.querySelector('.head h2');if(!h||h.textContent!=='Settings'||app.querySelector('.personalization-card'))return;const page=app.querySelector('.page');if(page)page.append(wallpaperPanel())}
const mo=new MutationObserver(()=>{enhanceSettings();applyWallpaper()});mo.observe(app,{childList:true,subtree:true});
const hm=new MutationObserver(applyWallpaper);hm.observe(home,{attributes:true,attributeFilter:['class']});
function enhancePhotos(){const h=app.querySelector('.head h2');if(!h||h.textContent!=='Photos')return;const grid=app.querySelector('.pics');if(!grid||grid.dataset.enhanced==='1')return;grid.dataset.enhanced='1';grid.addEventListener('click',e=>{const img=e.target.closest('img');if(!img)return;const src=img.src;const overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;background:#000e;z-index:100;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:18px';const big=document.createElement('img');big.src=src;big.style.cssText='max-width:100%;max-height:76vh;object-fit:contain;border-radius:12px';const actions=document.createElement('div');actions.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:8px;width:100%;max-width:420px;margin-top:16px';const del=document.createElement('button');del.className='primary';del.style.background='#d33';del.textContent='Delete';del.onclick=()=>{let a=[];try{a=JSON.parse(localStorage.getItem('pics')||'[]')}catch{}const raw=img.getAttribute('src');let j=a.indexOf(raw);if(j<0)j=a.findIndex(x=>src.endsWith(x));if(j>=0)a.splice(j,1);localStorage.setItem('pics',JSON.stringify(a));img.remove();overlay.remove();toast('Photo deleted')};const close=document.createElement('button');close.className='primary';close.style.background='#777';close.textContent='Close';close.onclick=()=>overlay.remove();actions.append(del,close);overlay.append(big,actions);document.body.append(overlay)});}
const photoMo=new MutationObserver(()=>{enhancePhotos();enhanceSettings()});photoMo.observe(app,{childList:true,subtree:true});
applyWallpaper();
window.CalculatorPersonalize={apply:applyWallpaper,panel:wallpaperPanel,presets};
})();
