(()=>{
const home=document.getElementById('home'),app=document.getElementById('app');
if(!home||!app)return;
const presets={
 mountains:'url("./calculator/wallpapers/mountains-photo-v50.jpg")',
 ocean:'url("./calculator/wallpapers/ocean-photo-v50.jpg")',
 forest:'url("./calculator/wallpapers/forest-photo-v50.jpg")',
 sunset:'url("./calculator/wallpapers/sunset-photo-v50.jpg")',
 night:'url("./calculator/wallpapers/night-photo-v50.jpg")',
 dark:'linear-gradient(165deg,#151a25,#07090f)'
};
function shell(){return home.querySelector('.phone-shell')}
function applyWallpaper(){const s=shell();if(!s)return;const image=localStorage.getItem('phone-wallpaper-image');const preset=localStorage.getItem('phone-wallpaper-preset')||'mountains';if(image){s.style.backgroundImage=`url(${JSON.stringify(image)})`;s.style.backgroundSize='cover';s.style.backgroundPosition='center';}else{s.style.backgroundImage=presets[preset]||presets.mountains;s.style.backgroundSize='cover';s.style.backgroundPosition='center'}}
function toast(m){const t=document.getElementById('toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1200)}
function compress(file,max=1000,quality=.78){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=reject;fr.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',quality))};img.src=fr.result};fr.readAsDataURL(file)})}
function setWallpaper(src){if(src){try{localStorage.setItem('phone-wallpaper-image',src)}catch{toast('That photo is too large');return}}else localStorage.removeItem('phone-wallpaper-image');applyWallpaper();toast('Wallpaper changed')}
function presetButton(name,label,bg){const b=document.createElement('button');b.type='button';b.style.cssText=`height:92px;border-radius:17px;background:${bg};color:white;font-weight:800;text-shadow:0 1px 4px #0008`;b.textContent=label;b.onclick=()=>{localStorage.setItem('phone-wallpaper-preset',name);localStorage.removeItem('phone-wallpaper-image');applyWallpaper();toast('Wallpaper changed')};return b}
function wallpaperPanel(){const wrap=document.createElement('div');wrap.className='card personalization-card';const title=document.createElement('strong');title.textContent='Choose a Background';const sub=document.createElement('div');sub.className='muted';sub.textContent='Pick a sharp photo or use one of your own.';const grid=document.createElement('div');grid.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:12px';grid.append(presetButton('mountains','Mountains',presets.mountains),presetButton('ocean','Ocean',presets.ocean),presetButton('forest','Forest',presets.forest),presetButton('sunset','Sunset',presets.sunset),presetButton('night','Night Sky',presets.night),presetButton('dark','Midnight',presets.dark));const label=document.createElement('label');label.style.cssText='display:block;margin-top:12px;background:#0a84ff;color:white;padding:12px 14px;border-radius:13px;font-weight:800;text-align:center;box-shadow:0 6px 12px #1113';label.textContent='Choose My Photo';const inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.hidden=true;label.append(inp);inp.onchange=async()=>{const f=inp.files&&inp.files[0];if(!f)return;try{setWallpaper(await compress(f))}catch{toast('Could not use that photo')}inp.value=''};const clear=document.createElement('button');clear.className='reset';clear.textContent='Use Built-in Background';clear.onclick=()=>{localStorage.removeItem('phone-wallpaper-image');localStorage.setItem('phone-wallpaper-preset','mountains');applyWallpaper();toast('Built-in background restored')};wrap.append(title,sub,grid,label,clear);return wrap}
function enhanceSettings(){const h=app.querySelector('.head h2');if(!h||h.textContent!=='Settings'||app.querySelector('.personalization-card'))return;const page=app.querySelector('.page');if(page)page.append(wallpaperPanel())}
const mo=new MutationObserver(()=>{enhanceSettings();applyWallpaper()});mo.observe(app,{childList:true,subtree:true});
const hm=new MutationObserver(applyWallpaper);hm.observe(home,{attributes:true,attributeFilter:['class']});
function enhancePhotos(){const h=app.querySelector('.head h2');if(!h||h.textContent!=='Photos')return;const grid=app.querySelector('.pics');if(!grid||grid.dataset.enhanced==='1')return;grid.dataset.enhanced='1';grid.addEventListener('click',e=>{const img=e.target.closest('img');if(!img)return;const src=img.src;const overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;background:#000e;z-index:100;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:18px';const big=document.createElement('img');big.src=src;big.style.cssText='max-width:100%;max-height:76vh;object-fit:contain;border-radius:12px';const actions=document.createElement('div');actions.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:8px;width:100%;max-width:420px;margin-top:16px';const del=document.createElement('button');del.className='primary';del.style.background='#d33';del.textContent='Delete';del.onclick=()=>{let a=[];try{a=JSON.parse(localStorage.getItem('pics')||'[]')}catch{}const raw=img.getAttribute('src');let j=a.indexOf(raw);if(j<0)j=a.findIndex(x=>src.endsWith(x));if(j>=0)a.splice(j,1);localStorage.setItem('pics',JSON.stringify(a));img.remove();overlay.remove();toast('Photo deleted')};const close=document.createElement('button');close.className='primary';close.style.background='#777';close.textContent='Close';close.onclick=()=>overlay.remove();actions.append(del,close);overlay.append(big,actions);document.body.append(overlay)});}
const photoMo=new MutationObserver(()=>{enhancePhotos();enhanceSettings()});photoMo.observe(app,{childList:true,subtree:true});
applyWallpaper();
window.CalculatorPersonalize={apply:applyWallpaper,panel:wallpaperPanel,presets};
})();
