(()=>{
if(!(window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true))return;
if(!window.supabase||!window.supabase.createClient)return;
const SUPABASE_URL='https://nzwygirmuolgwwvtjexw.supabase.co';
const SUPABASE_KEY='sb_publishable_cgOv1kSk43tKAO62az5EgQ_ieMN0_-c';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{realtime:{params:{eventsPerSecond:10}}});
const home=document.getElementById('home'),app=document.getElementById('app'),toastEl=document.getElementById('toast');
if(!home||!app)return;
const state={inbox:null,pc:null,dc:null,local:null,remote:new MediaStream(),callId:null,peer:null,callKey:null,pending:null,active:false};
function toast(m){if(!toastEl)return;toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1400)}
function show(el){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
function backHome(){show(home)}
function calcNumber(){let n=localStorage.getItem('calculator-number');if(!n){const a=new Uint32Array(2);crypto.getRandomValues(a);n=String((a[0]%900)+100)+'-'+String(a[1]%1000).padStart(3,'0')+'-'+String((a[0]^a[1])%10000).padStart(4,'0');localStorage.setItem('calculator-number',n)}return n}
function cleanNumber(s){return String(s||'').replace(/\D/g,'')}
function topicFor(n){return 'calc-phone-'+cleanNumber(n)}
function contacts(){try{return JSON.parse(localStorage.getItem('calculator-contacts')||'[]')}catch{return[]}}
function saveContacts(a){localStorage.setItem('calculator-contacts',JSON.stringify(a.slice(0,100)))}
function recents(){try{return JSON.parse(localStorage.getItem('calculator-recents')||'[]')}catch{return[]}}
function addRecent(number,type){const a=recents();a.unshift({number,type,time:Date.now()});localStorage.setItem('calculator-recents',JSON.stringify(a.slice(0,40)))}
function nav(title){const h=document.createElement('div');h.className='ios-nav';const b=document.createElement('button');b.className='ios-back';b.textContent='‹ Home';b.onclick=backHome;const t=document.createElement('h2');t.textContent=title;h.append(b,t);return h}
function phoneIcon(){const b=document.createElement('button');b.className='phone-app calculator-phone-launch';b.innerHTML='<span class="phone-icon phone-green">☎</span><span class="phone-label">Phone</span>';b.onclick=openPhone;return b}
function contactsIcon(){const b=document.createElement('button');b.className='phone-app calculator-contacts-launch';b.innerHTML='<span class="phone-icon contacts-icon">👤</span><span class="phone-label">Contacts</span>';b.onclick=openContacts;return b}
function numberIcon(){const b=document.createElement('button');b.className='phone-app calculator-number-launch';b.innerHTML='<span class="phone-icon number-icon">#</span><span class="phone-label">My Number</span>';b.onclick=openNumber;return b}
function inject(){const pages=document.getElementById('phonePages');if(!pages)return;const grids=pages.querySelectorAll('.phone-grid');if(!grids.length)return;const g0=grids[0],g1=grids[1]||g0;if(!pages.querySelector('.calculator-phone-launch'))g0.prepend(phoneIcon());if(!pages.querySelector('.calculator-contacts-launch'))g1.prepend(contactsIcon());if(!pages.querySelector('.calculator-number-launch'))g1.prepend(numberIcon())}
new MutationObserver(inject).observe(document.getElementById('phonePages'),{childList:true,subtree:true});inject();

async function startInbox(){if(state.inbox)return;const topic=topicFor(calcNumber());const ch=sb.channel(topic,{config:{broadcast:{ack:true}}});ch.on('broadcast',{event:'call'},p=>onIncomingCall(p.payload)).on('broadcast',{event:'secure'},p=>onSecureSignal(p.payload)).on('broadcast',{event:'hangup'},p=>onHangup(p.payload));state.inbox=ch;ch.subscribe(s=>{if(s==='SUBSCRIBED')console.log('Calculator Phone ready')})}
startInbox();

async function ecKeyPair(){return crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveKey','deriveBits'])}
async function exportPub(k){const raw=new Uint8Array(await crypto.subtle.exportKey('raw',k));return b64(raw)}
async function importPub(s){return crypto.subtle.importKey('raw',unb64(s),{name:'ECDH',namedCurve:'P-256'},true,[])}
async function deriveAes(priv,pubString){const pub=await importPub(pubString);return crypto.subtle.deriveKey({name:'ECDH',public:pub},priv,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function b64(u){let s='';for(let i=0;i<u.length;i+=8192)s+=String.fromCharCode(...u.subarray(i,i+8192));return btoa(s)}function unb64(s){const x=atob(s),u=new Uint8Array(x.length);for(let i=0;i<x.length;i++)u[i]=x.charCodeAt(i);return u}
async function seal(key,obj){const iv=crypto.getRandomValues(new Uint8Array(12));const data=new TextEncoder().encode(JSON.stringify(obj));const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data));return{iv:b64(iv),data:b64(ct)}}
async function openSeal(key,p){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(p.iv)},key,unb64(p.data));return JSON.parse(new TextDecoder().decode(pt))}
async function sendTo(number,event,payload){const ch=sb.channel(topicFor(number));await ch.httpSend(event,payload);await sb.removeChannel(ch)}

function makePC(){if(state.pc)try{state.pc.close()}catch{}const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});state.pc=pc;state.remote=new MediaStream();pc.ontrack=e=>{e.streams[0]?.getTracks().forEach(t=>{if(!state.remote.getTracks().some(x=>x.id===t.id))state.remote.addTrack(t)});renderCallMedia()};pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected'){state.active=true;setCallStatus('Connected')}if(['failed','closed','disconnected'].includes(pc.connectionState)&&state.active)endCall(false)};pc.ondatachannel=e=>{state.dc=e.channel;wireDC()};return pc}
function wireDC(){if(!state.dc)return;state.dc.onopen=()=>toast('Secure connection ready');state.dc.onmessage=e=>window.dispatchEvent(new CustomEvent('calculator-phone-data',{detail:e.data}))}
function waitIce(pc){return new Promise(res=>{if(pc.iceGatheringState==='complete')return res();const f=()=>{if(pc.iceGatheringState==='complete'){pc.removeEventListener('icegatheringstatechange',f);res()}};pc.addEventListener('icegatheringstatechange',f);setTimeout(res,4500)})}

async function callNumber(number,video=false){number=normalizeDisplay(number);if(!cleanNumber(number))return toast('Enter a Calculator Number');if(cleanNumber(number)===cleanNumber(calcNumber()))return toast('That is your own number');const callId=crypto.randomUUID(),keys=await ecKeyPair();state.callId=callId;state.peer=number;state.pending={role:'caller',keys,video};showOutgoing(number,video);await sendTo(number,'call',{callId,from:calcNumber(),pub:await exportPub(keys.publicKey),video,at:Date.now()});addRecent(number,'outgoing')}
async function onIncomingCall(m){if(!m||!m.callId||m.from===calcNumber())return;if(state.callId)return;state.callId=m.callId;state.peer=m.from;state.pending={role:'callee',callerPub:m.pub,video:!!m.video};showIncoming(m.from,!!m.video)}
async function acceptIncoming(){const p=state.pending;if(!p||p.role!=='callee')return;try{const keys=await ecKeyPair();state.callKey=await deriveAes(keys.privateKey,p.callerPub);state.pending.keys=keys;const pc=makePC();const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:p.video});state.local=stream;stream.getTracks().forEach(t=>pc.addTrack(t,stream));await sendTo(state.peer,'secure',{callId:state.callId,from:calcNumber(),kind:'accept',pub:await exportPub(keys.publicKey)});setCallStatus('Connecting…');renderCallMedia();addRecent(state.peer,'incoming')}catch{toast('Microphone/camera permission is needed');endCall(true)}}
async function onSecureSignal(m){if(!m||m.callId!==state.callId||m.from!==state.peer)return;try{if(m.kind==='accept'&&state.pending?.role==='caller'){state.callKey=await deriveAes(state.pending.keys.privateKey,m.pub);const pc=makePC();const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:state.pending.video});state.local=stream;stream.getTracks().forEach(t=>pc.addTrack(t,stream));state.dc=pc.createDataChannel('calculator-secure',{ordered:true});wireDC();const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);await sendTo(state.peer,'secure',{callId:state.callId,from:calcNumber(),kind:'sealed',box:await seal(state.callKey,{type:'offer',desc:pc.localDescription})});setCallStatus('Ringing…')}
else if(m.kind==='sealed'&&state.callKey){const x=await openSeal(state.callKey,m.box);if(x.type==='offer'&&state.pending?.role==='callee'){await state.pc.setRemoteDescription(x.desc);const ans=await state.pc.createAnswer();await state.pc.setLocalDescription(ans);await waitIce(state.pc);await sendTo(state.peer,'secure',{callId:state.callId,from:calcNumber(),kind:'sealed',box:await seal(state.callKey,{type:'answer',desc:state.pc.localDescription})})}else if(x.type==='answer'&&state.pending?.role==='caller'){await state.pc.setRemoteDescription(x.desc)}}}catch(e){console.error(e);toast('Could not establish secure call')}}
async function declineIncoming(){if(state.peer)await sendTo(state.peer,'hangup',{callId:state.callId,from:calcNumber(),reason:'declined'}).catch(()=>{});endCall(false)}
async function onHangup(m){if(m?.callId===state.callId)endCall(false)}
async function endCall(send=true){const id=state.callId,peer=state.peer;if(send&&id&&peer)sendTo(peer,'hangup',{callId:id,from:calcNumber(),reason:'ended'}).catch(()=>{});if(state.local)state.local.getTracks().forEach(t=>t.stop());if(state.pc)try{state.pc.close()}catch{}Object.assign(state,{pc:null,dc:null,local:null,remote:new MediaStream(),callId:null,peer:null,callKey:null,pending:null,active:false});document.getElementById('calcCallOverlay')?.remove();if(!document.querySelector('.screen.active'))show(home)}

function overlayBase(){document.getElementById('calcCallOverlay')?.remove();const o=document.createElement('div');o.id='calcCallOverlay';o.className='calc-call-overlay';document.body.append(o);return o}
function showOutgoing(number,video){const o=overlayBase();o.innerHTML=`<div class="call-avatar">#</div><div class="call-name">${escapeHtml(contactName(number)||number)}</div><div id="callStatus" class="call-status">Calling Calculator…</div><div class="call-actions"><button id="callEnd" class="call-circle danger">✕</button></div>`;o.querySelector('#callEnd').onclick=()=>endCall(true)}
function showIncoming(number,video){const o=overlayBase();o.innerHTML=`<div class="call-small">Incoming ${video?'video ':''}Calculator call</div><div class="call-avatar">#</div><div class="call-name">${escapeHtml(contactName(number)||number)}</div><div class="call-status">Calculator ${escapeHtml(number)}</div><div class="incoming-actions"><button id="decline" class="call-circle danger">✕</button><button id="accept" class="call-circle accept">✓</button></div>`;o.querySelector('#decline').onclick=declineIncoming;o.querySelector('#accept').onclick=acceptIncoming;try{navigator.vibrate?.([300,180,300,180,300])}catch{}}
function renderCallMedia(){const o=document.getElementById('calcCallOverlay')||overlayBase();if(state.pending?.video){o.classList.add('video-call');let rv=o.querySelector('#remoteCallVideo');if(!rv){rv=document.createElement('video');rv.id='remoteCallVideo';rv.autoplay=true;rv.playsInline=true;rv.className='remote-call-video';o.prepend(rv)}rv.srcObject=state.remote;let lv=o.querySelector('#localCallVideo');if(!lv){lv=document.createElement('video');lv.id='localCallVideo';lv.autoplay=true;lv.muted=true;lv.playsInline=true;lv.className='local-call-video';o.append(lv)}lv.srcObject=state.local}if(!o.querySelector('#callEnd')){const end=document.createElement('button');end.id='callEnd';end.className='call-circle danger floating-end';end.textContent='✕';end.onclick=()=>endCall(true);o.append(end)}}
function setCallStatus(s){const e=document.getElementById('callStatus');if(e)e.textContent=s}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function normalizeDisplay(v){const d=cleanNumber(v).slice(0,10);if(d.length<=3)return d;if(d.length<=6)return d.slice(0,3)+'-'+d.slice(3);return d.slice(0,3)+'-'+d.slice(3,6)+'-'+d.slice(6)}
function contactName(n){return contacts().find(c=>cleanNumber(c.number)===cleanNumber(n))?.name||''}

function openNumber(){app.innerHTML='';const r=document.createElement('div');r.className='ios-app';r.append(nav('My Calculator Number'));const c=document.createElement('div');c.className='ios-card number-card';c.innerHTML=`<div class="number-hash">#</div><div class="number-title">Your Calculator Number</div><div class="calculator-number">${calcNumber()}</div><div class="privacy-note">Give this number only to people you want to reach you inside Calculator. Calls ring while this Calculator app is open.</div>`;const copy=document.createElement('button');copy.className='primary';copy.textContent='Copy Number';copy.onclick=()=>navigator.clipboard.writeText(calcNumber()).then(()=>toast('Number copied'));c.append(copy);r.append(c);app.append(r);show(app)}
function openPhone(){app.innerHTML='';const r=document.createElement('div');r.className='phone-app-page';r.append(nav('Phone'));const display=document.createElement('div');display.className='dial-number';display.textContent='';const keys=document.createElement('div');keys.className='dialpad';'123456789*0#'.split('').forEach(k=>{const b=document.createElement('button');b.className='dial-key';b.textContent=k;b.onclick=()=>{if(k==='*'||k==='#')return;display.textContent=normalizeDisplay(display.textContent+k)}});const actions=document.createElement('div');actions.className='dial-actions';const del=document.createElement('button');del.className='dial-delete';del.textContent='⌫';del.onclick=()=>display.textContent=normalizeDisplay(cleanNumber(display.textContent).slice(0,-1));const call=document.createElement('button');call.className='dial-call';call.textContent='☎';call.onclick=()=>callNumber(display.textContent,false);const video=document.createElement('button');video.className='dial-video';video.textContent='▣';video.onclick=()=>callNumber(display.textContent,true);actions.append(del,call,video);const mine=document.createElement('button');mine.className='my-number-chip';mine.textContent='My number: '+calcNumber();mine.onclick=openNumber;const recentTitle=document.createElement('div');recentTitle.className='ios-section-title';recentTitle.textContent='Recents';const recent=document.createElement('div');recent.className='ios-card';const rs=recents();recent.innerHTML=rs.length?rs.slice(0,6).map(x=>`<div class="contact-row"><div><strong>${escapeHtml(contactName(x.number)||x.number)}</strong><div class="privacy-note">${x.type} · ${new Date(x.time).toLocaleString()}</div></div><button data-call="${escapeHtml(x.number)}" class="mini-call">☎</button></div>`).join(''):'<div class="privacy-note">No calls yet.</div>';recent.onclick=e=>{const b=e.target.closest('[data-call]');if(b)callNumber(b.dataset.call,false)};r.append(display,keys,actions,mine,recentTitle,recent);app.append(r);show(app)}
function openContacts(){app.innerHTML='';const r=document.createElement('div');r.className='ios-app';r.append(nav('Contacts'));const add=document.createElement('button');add.className='primary';add.textContent='+ New Calculator Contact';add.onclick=()=>{const name=prompt('Name:');if(!name)return;const num=normalizeDisplay(prompt('Calculator Number:')||'');if(cleanNumber(num).length<7)return toast('Enter the Calculator Number');const a=contacts();a.push({id:crypto.randomUUID(),name:name.trim(),number:num});saveContacts(a);openContacts()};r.append(add);const list=document.createElement('div');list.className='ios-card contact-list';const a=contacts().sort((x,y)=>x.name.localeCompare(y.name));list.innerHTML=a.length?'':'<div class="privacy-note">No Calculator contacts yet.</div>';a.forEach(c=>{const row=document.createElement('div');row.className='contact-row';const info=document.createElement('button');info.className='contact-info';info.innerHTML=`<span class="contact-avatar">${escapeHtml(c.name.slice(0,1).toUpperCase())}</span><span><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.number)}</small></span>`;info.onclick=()=>openContact(c);const cb=document.createElement('button');cb.className='mini-call';cb.textContent='☎';cb.onclick=()=>callNumber(c.number,false);row.append(info,cb);list.append(row)});r.append(list);app.append(r);show(app)}
function openContact(c){app.innerHTML='';const r=document.createElement('div');r.className='ios-app';r.append(nav(c.name));const card=document.createElement('div');card.className='ios-card contact-detail';card.innerHTML=`<div class="big-contact-avatar">${escapeHtml(c.name.slice(0,1).toUpperCase())}</div><h2>${escapeHtml(c.name)}</h2><div class="calculator-number">${escapeHtml(c.number)}</div>`;const a=document.createElement('div');a.className='contact-actions';const call=document.createElement('button');call.textContent='☎ Call';call.onclick=()=>callNumber(c.number,false);const vid=document.createElement('button');vid.textContent='▣ Video';vid.onclick=()=>callNumber(c.number,true);const msg=document.createElement('button');msg.textContent='● Message';msg.onclick=()=>window.dispatchEvent(new CustomEvent('calculator-secret-message-number',{detail:c.number}));a.append(call,vid,msg);card.append(a);r.append(card);app.append(r);show(app)}

window.CalculatorPhone={number:calcNumber,call:callNumber,contacts,sendData:(x)=>{if(state.dc?.readyState==='open')state.dc.send(typeof x==='string'?x:JSON.stringify(x));else toast('No secure phone connection is open')},state};
window.addEventListener('calculator-private-home',inject);
})();