(()=>{
if(!(window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true))return;
if(!window.supabase?.createClient)return;
const sb=window.supabase.createClient('https://nzwygirmuolgwwvtjexw.supabase.co','sb_publishable_cgOv1kSk43tKAO62az5EgQ_ieMN0_-c',{realtime:{params:{eventsPerSecond:10}}});
const home=document.getElementById('home'),app=document.getElementById('app'),toastEl=document.getElementById('toast');if(!home||!app)return;
let activePeer='';
function toast(m){toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1200)}
function show(el){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
function backHome(){show(home)}
function clean(s){return String(s||'').replace(/\D/g,'').slice(0,10)}
function format(s){const d=clean(s);if(d.length<=3)return d;if(d.length<=6)return d.slice(0,3)+'-'+d.slice(3);return d.slice(0,3)+'-'+d.slice(3,6)+'-'+d.slice(6)}
function myNumber(){let n=localStorage.getItem('calculator-number');if(!n){const a=new Uint32Array(2);crypto.getRandomValues(a);n=String((a[0]%900)+100)+'-'+String(a[1]%1000).padStart(3,'0')+'-'+String((a[0]^a[1])%10000).padStart(4,'0');localStorage.setItem('calculator-number',n)}return n}
function codeName(){return localStorage.getItem('calculator-codename')||'Private User'}
function topic(n){return 'calc-phone-'+clean(n)}
function contacts(){try{return JSON.parse(localStorage.getItem('calculator-contacts')||'[]')}catch{return[]}}
function contactName(n){return contacts().find(c=>clean(c.number)===clean(n))?.name||''}
function threads(){try{return JSON.parse(localStorage.getItem('calculator-number-texts')||'{}')}catch{return{}}}
function saveThreads(v){localStorage.setItem('calculator-number-texts',JSON.stringify(v))}
function addMsg(peer,msg){const all=threads(),k=clean(peer);all[k]=all[k]||[];all[k].push(msg);all[k]=all[k].slice(-250);saveThreads(all);if(activePeer===k)renderConversation(format(k))}
function nav(title){const h=document.createElement('div');h.className='ios-nav';const b=document.createElement('button');b.className='ios-back';b.textContent='‹ Home';b.onclick=backHome;const t=document.createElement('h2');t.textContent=title;h.append(b,t);return h}
async function sendEvent(number,event,payload){const ch=sb.channel(topic(number));try{await ch.httpSend(event,payload)}finally{await sb.removeChannel(ch)}}
const inbox=sb.channel(topic(myNumber()),{config:{broadcast:{ack:true}}});
inbox.on('broadcast',{event:'text'},p=>{const m=p.payload;if(!m||clean(m.from)===clean(myNumber()))return;addMsg(m.from,{id:m.id||crypto.randomUUID(),mine:false,text:String(m.text||'').slice(0,5000),time:m.time||Date.now(),name:String(m.name||'Private User').slice(0,30),number:format(m.from)});toast('Secret Message from '+(m.name||format(m.from)))}).on('broadcast',{event:'caller-id'},p=>{const m=p.payload;if(!m?.from)return;sessionStorage.setItem('caller-name-'+clean(m.from),String(m.name||'Private User').slice(0,30))}).subscribe();
function openMessages(){app.innerHTML='';activePeer='';const root=document.createElement('div');root.className='ios-app clean-messages';root.append(nav('Secret Message'));const identity=document.createElement('div');identity.className='message-identity';identity.innerHTML='<div><strong></strong><span></span></div><button>New Message</button>';identity.querySelector('strong').textContent=codeName();identity.querySelector('span').textContent='Calculator '+myNumber();identity.querySelector('button').onclick=()=>openNewMessage();root.append(identity);const title=document.createElement('div');title.className='ios-section-title';title.textContent='Messages';root.append(title);const list=document.createElement('div');list.className='message-list';const all=threads(),keys=Object.keys(all).filter(k=>all[k]?.length).sort((a,b)=>(all[b].at(-1)?.time||0)-(all[a].at(-1)?.time||0));if(!keys.length){const empty=document.createElement('div');empty.className='ios-card privacy-note';empty.textContent='No messages yet. Tap New Message and enter a Calculator Number.';list.append(empty)}keys.forEach(k=>{const last=all[k].at(-1),name=contactName(k)||last.name||format(k),row=document.createElement('button');row.className='message-list-row';row.innerHTML='<div class="message-avatar"></div><div class="message-summary"><strong></strong><span></span></div><div class="message-chevron">›</div>';row.querySelector('.message-avatar').textContent=(name[0]||'#').toUpperCase();row.querySelector('strong').textContent=name;row.querySelector('span').textContent=last.text||'Message';row.onclick=()=>renderConversation(format(k));list.append(row)});root.append(list);app.append(root);show(app)}
function openNewMessage(prefill=''){app.innerHTML='';const root=document.createElement('div');root.className='ios-app new-message-page';root.append(nav('New Message'));const card=document.createElement('div');card.className='ios-card';const lab=document.createElement('label');lab.className='to-label';lab.textContent='To:';const input=document.createElement('input');input.className='number-entry';input.inputMode='numeric';input.placeholder='Calculator Number';input.value=prefill;input.oninput=()=>input.value=format(input.value);const next=document.createElement('button');next.className='primary';next.textContent='Message';next.onclick=()=>{if(clean(input.value).length!==10)return toast('Enter a full Calculator Number');renderConversation(input.value)};card.append(lab,input,next);root.append(card);app.append(root);show(app);input.focus()}
function renderConversation(number){number=format(number);activePeer=clean(number);app.innerHTML='';const root=document.createElement('div');root.className='ios-app conversation-page';const h=nav(contactName(number)||number),sub=document.createElement('div');sub.className='conversation-subtitle';sub.textContent='Calculator '+number;h.append(sub);root.append(h);const thread=document.createElement('div');thread.className='messages-thread clean-thread';for(const m of (threads()[clean(number)]||[])){const row=document.createElement('div');row.className='bubble-row '+(m.mine?'me':'them');const b=document.createElement('div');b.className='msg-bubble';const t=document.createElement('div');t.textContent=m.text;b.append(t);const tm=document.createElement('div');tm.className='msg-time';tm.textContent=new Date(m.time).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});b.append(tm);row.append(b);thread.append(row)}root.append(thread);const comp=document.createElement('div');comp.className='composer safe-composer';const input=document.createElement('input');input.placeholder='Secret Message';const send=document.createElement('button');send.textContent='↑';send.onclick=async()=>{const text=input.value.trim();if(!text)return;const msg={id:crypto.randomUUID(),mine:true,text,time:Date.now(),name:codeName(),number:myNumber()};addMsg(number,msg);input.value='';try{await sendEvent(number,'text',{id:msg.id,from:myNumber(),name:codeName(),text,time:msg.time})}catch{toast('Message could not be delivered')}};input.onkeydown=e=>{if(e.key==='Enter')send.click()};comp.append(input,send);root.append(comp);app.append(root);show(app);requestAnimationFrame(()=>{thread.scrollTop=thread.scrollHeight});input.focus()}
function enhanceMyNumber(){const card=app.querySelector('.number-card');if(!card||card.querySelector('.codename-box'))return;const box=document.createElement('div');box.className='codename-box';const label=document.createElement('label');label.textContent='Code Name';const i=document.createElement('input');i.className='field';i.maxLength=30;i.value=codeName();i.placeholder='Choose a code name';const save=document.createElement('button');save.className='primary';save.textContent='Save Code Name';save.onclick=()=>{const v=i.value.trim();if(!v)return toast('Enter a code name');localStorage.setItem('calculator-codename',v.slice(0,30));toast('Code name saved')};box.append(label,i,save);card.prepend(box)}
function enhancePhone(){const page=app.querySelector('.phone-app-page');if(!page||page.dataset.polished==='1')return;page.dataset.polished='1';const display=page.querySelector('.dial-number'),actions=page.querySelector('.dial-actions');if(!display||!actions)return;const call=actions.querySelector('.dial-call'),video=actions.querySelector('.dial-video');if(call){const old=call.onclick;call.onclick=async e=>{if(clean(display.textContent).length!==10)return toast('Enter a full Calculator Number');sendEvent(display.textContent,'caller-id',{from:myNumber(),name:codeName(),time:Date.now()}).catch(()=>{});old?.call(call,e)}}if(video){video.textContent='✉';video.className='dial-message';video.setAttribute('aria-label','Message');video.onclick=()=>{if(clean(display.textContent).length!==10)return toast('Enter a full Calculator Number');openNewMessage(display.textContent)}}const mine=page.querySelector('.my-number-chip');if(mine)mine.textContent=codeName()+' · '+myNumber()}
function polishIncoming(){const o=document.getElementById('calcCallOverlay');if(!o||!o.querySelector('#accept'))return;const status=o.querySelector('.call-status'),number=(status?.textContent.match(/[0-9]{3}-[0-9]{3}-[0-9]{4}/)||[])[0];if(number){const nm=sessionStorage.getItem('caller-name-'+clean(number));const name=o.querySelector('.call-name');if(nm&&name)name.textContent=nm}}
const observer=new MutationObserver(()=>{enhanceMyNumber();enhancePhone();polishIncoming()});observer.observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',e=>{const b=e.target.closest('.phone-app');if(!b)return;const label=b.querySelector('.phone-label')?.textContent;if(label==='Secret Message'){e.preventDefault();e.stopImmediatePropagation();openMessages()}},true);
})();