(()=>{
const pages=document.getElementById('phonePages'),dock=document.getElementById('phoneDock'),app=document.getElementById('app'),home=document.getElementById('home'),toastEl=document.getElementById('toast');if(!pages||!app||!home)return;
const DB='calculator-private-storage-v1';let stream=null,facing='environment',opening=false;
const show=el=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));el.classList.add('active')};
const toast=m=>{if(!toastEl)return;toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),900)};
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('files'))d.createObjectStore('files',{keyPath:'id'});if(!d.objectStoreNames.contains('photos'))d.createObjectStore('photos',{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function all(){const d=await db();return new Promise((res,rej)=>{const r=d.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function put(v){const d=await db();return new Promise((res,rej)=>{const r=d.transaction('photos','readwrite').objectStore('photos').put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function del(id){const d=await db();return new Promise((res,rej)=>{const r=d.transaction('photos','readwrite').objectStore('photos').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function latest(){const a=(await all()).sort((x,y)=>y.time-x.time);return a[0]||null}
function photoButton(b){return b?.querySelector('.phone-label')?.textContent?.trim()==='Photos'}
async function setThumb(btn){const x=await latest();btn.innerHTML='';if(!x){btn.textContent='▦';return}const im=document.createElement('img');im.src=URL.createObjectURL(x.blob);im.onload=()=>setTimeout(()=>URL.revokeObjectURL(im.src),5000);btn.append(im)}
async function openCamera(){if(opening)return;opening=true;stopCamera();app.innerHTML='';const page=document.createElement('div');page.className='private-camera-page';const video=document.createElement('video');video.className='private-camera-video';video.autoplay=true;video.playsInline=true;video.muted=true;const topShade=document.createElement('div');topShade.className='camera-shade-top';const bottomShade=document.createElement('div');bottomShade.className='camera-shade-bottom';const top=document.createElement('div');top.className='private-camera-top';const close=document.createElement('button');close.className='camera-round';close.textContent='‹';close.onclick=()=>{stopCamera();show(home)};const title=document.createElement('div');title.className='camera-title';title.textContent='PHOTO';const galleryTop=document.createElement('button');galleryTop.className='camera-round';galleryTop.textContent='▦';galleryTop.onclick=openGallery;top.append(close,title,galleryTop);const controls=document.createElement('div');controls.className='private-camera-controls';const thumb=document.createElement('button');thumb.className='camera-thumb';thumb.onclick=openGallery;const shutter=document.createElement('button');shutter.className='private-camera-shutter';shutter.setAttribute('aria-label','Shutter');const flip=document.createElement('button');flip.className='camera-flip';flip.textContent='↻';flip.setAttribute('aria-label','Flip camera');controls.append(thumb,shutter,flip);const flash=document.createElement('div');flash.className='camera-flash';page.append(video,topShade,bottomShade,top,controls,flash);app.append(page);show(app);await setThumb(thumb);
 try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=stream;await video.play()}catch(e){console.warn('Camera unavailable',e);const err=document.createElement('div');err.className='camera-error';err.innerHTML='<div><div style="font-size:48px">📷</div><h2>Camera needs permission</h2><p>Allow camera access for Calculator in iPhone Settings, then try again.</p></div>';const g=document.createElement('button');g.textContent='Open Photos';g.onclick=openGallery;err.firstElementChild.append(g);page.append(err)}finally{opening=false}
 flip.onclick=async()=>{facing=facing==='environment'?'user':'environment';opening=false;await openCamera()};
 shutter.onclick=async()=>{if(!video.videoWidth||!video.videoHeight)return toast('Camera is starting');const c=document.createElement('canvas');c.width=video.videoWidth;c.height=video.videoHeight;const x=c.getContext('2d');if(facing==='user'){x.translate(c.width,0);x.scale(-1,1)}x.drawImage(video,0,0,c.width,c.height);c.toBlob(async blob=>{if(!blob)return;const item={id:crypto.randomUUID(),name:'Photo '+new Date().toLocaleString()+'.jpg',type:'image/jpeg',size:blob.size,time:Date.now(),blob,source:'camera'};await put(item);flash.classList.remove('go');void flash.offsetWidth;flash.classList.add('go');try{navigator.vibrate?.(25)}catch{}await setThumb(thumb)},'image/jpeg',.94)}
}
async function openGallery(){stopCamera();opening=false;app.innerHTML='';const page=document.createElement('div');page.className='photos-page';const nav=document.createElement('div');nav.className='photos-nav';const back=document.createElement('button');back.textContent='‹ Home';back.onclick=()=>show(home);const title=document.createElement('strong');title.textContent='Photos';const camera=document.createElement('button');camera.textContent='📷';camera.onclick=openCamera;nav.append(back,title,camera);const heading=document.createElement('div');heading.className='photos-heading';const h=document.createElement('h1');h.textContent='Library';const count=document.createElement('span');heading.append(h,count);const grid=document.createElement('div');grid.className='photos-grid';const fab=document.createElement('button');fab.className='photos-camera-fab';fab.textContent='📷';fab.onclick=openCamera;page.append(nav,heading,grid,fab);app.append(page);show(app);const items=(await all()).sort((a,b)=>b.time-a.time);count.textContent=items.length+(items.length===1?' Photo':' Photos');if(!items.length){const empty=document.createElement('div');empty.className='photos-empty';empty.innerHTML='<span class="big">📷</span><strong>No Photos Yet</strong><div>Tap the camera to take your first photo.</div>';page.insertBefore(empty,fab);return}for(const item of items){const tile=document.createElement('button');tile.className='photos-tile';const url=URL.createObjectURL(item.blob);const im=document.createElement('img');im.src=url;im.alt='Photo';tile.append(im);tile.onclick=()=>viewer(item,url);grid.append(tile)}}
function viewer(item,url){const v=document.createElement('div');v.className='photo-viewer';const im=document.createElement('img');im.src=url;const top=document.createElement('div');top.className='photo-viewer-top';const done=document.createElement('button');done.textContent='Done';done.onclick=()=>{v.remove();URL.revokeObjectURL(url)};top.append(done);const bottom=document.createElement('div');bottom.className='photo-viewer-bottom';const trash=document.createElement('button');trash.className='trash';trash.textContent='Delete';trash.onclick=async()=>{await del(item.id);v.remove();URL.revokeObjectURL(url);openGallery()};bottom.append(trash);v.append(im,top,bottom);document.body.append(v)}
function intercept(e){const b=e.target.closest?.('.phone-app');if(!photoButton(b))return;e.preventDefault();e.stopImmediatePropagation();openCamera()}
pages.addEventListener('click',intercept,true);dock?.addEventListener('click',intercept,true);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera()});window.addEventListener('pagehide',stopCamera);window.addEventListener('calculator-lock',stopCamera);window.CalculatorPrivatePhotos={openCamera,openGallery,stopCamera};
})();