(()=>{
const home=document.getElementById('home'),app=document.getElementById('app'),toastEl=document.getElementById('toast');
if(!home||!app)return;
const enc=new TextEncoder(),dec=new TextDecoder();
const RTC={pc:null,dc:null,remoteStream:null,audioSender:null,videoSender:null,localStream:null,connected:false};
function toast(m){if(!toastEl)return;toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1300)}
function show(el){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
function backHome(){show(home)}
function nav(title){const h=document.createElement('div');h.className='ios-nav';const b=document.createElement('button');b.className='ios-back';b.textContent='‹ Home';b.onclick=backHome;const t=document.createElement('h2');t.textContent=title;h.append(b,t);return h}
function iconButton(){const b=document.createElement('button');b.className='phone-app secret-message-launch';b.innerHTML='<span class="phone-icon messages-icon">●</span><span class="phone-label">Secret Message</span>';b.onclick=openMessages;return b}
function injectIcon(){const pages=document.getElementById('phonePages');if(!pages||pages.querySelector('.secret-message-launch'))return;const grids=pages.querySelectorAll('.phone-grid');const g=grids[1]||grids[0];if(g)g.prepend(iconButton())}
new MutationObserver(injectIcon).observe(document.getElementById('phonePages'),{childList:true,subtree:true});injectIcon();

function loadMessages(){try{const a=JSON.parse(localStorage.getItem('secret-message-history')||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function saveMessages(a){localStorage.setItem('secret-message-history',JSON.stringify(a.slice(-500)))}
function addMessage(m){const a=loadMessages();a.push({id:crypto.randomUUID(),time:Date.now(),...m});saveMessages(a);renderThread()}

function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('secret-message-files',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files',{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putBlob(blob,name,type,id=crypto.randomUUID()){const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put({id,blob,name,type,size:blob.size});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});return id}
async function getBlob(id){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('files','readonly'),r=tx.objectStore('files').get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}

let currentThread=null;
function openMessages(){app.innerHTML='';const root=document.createElement('div');root.className='ios-app messages-app';root.append(nav('Secret Message'));
 const tools=document.createElement('div');tools.className='ios-card';tools.innerHTML='<div style="display:flex;align-items:center;justify-content:space-between;gap:8px"><div><strong>Private phone-to-phone chat</strong><div class="privacy-note">Separate from iMessage and SMS. Use Connect to pair two phones directly.</div></div><button class="transfer-btn" id="smConnect">Connect</button></div><div class="transfer-row" style="margin-top:10px"><button class="transfer-btn" id="smAudio">☎ Call</button><button class="transfer-btn" id="smVideo">▣ Video</button></div><div class="transfer-row" style="margin-top:8px"><button class="transfer-btn" id="smExport">Export</button><button class="transfer-btn" id="smImport">Import</button></div>';
 root.append(tools);const thread=document.createElement('div');thread.id='secretThread';thread.className='messages-thread';root.append(thread);
 const comp=document.createElement('div');comp.className='composer';const attach=document.createElement('button');attach.textContent='＋';attach.style.background='#d1d1d6';attach.style.color='#111';const file=document.createElement('input');file.type='file';file.accept='image/*,video/*,audio/*';file.multiple=false;file.hidden=true;attach.append(file);const input=document.createElement('input');input.placeholder='Secret Message';const send=document.createElement('button');send.textContent='↑';comp.append(attach,input,send);root.append(comp);app.append(root);show(app);currentThread=thread;
 send.onclick=()=>{const text=input.value.trim();if(!text)return;sendText(text);input.value=''};input.onkeydown=e=>{if(e.key==='Enter')send.click()};file.onchange=async()=>{const f=file.files&&file.files[0];if(!f)return;await sendFile(f);file.value=''};
 root.querySelector('#smConnect').onclick=openConnect;root.querySelector('#smAudio').onclick=()=>startCall(false);root.querySelector('#smVideo').onclick=()=>startCall(true);root.querySelector('#smExport').onclick=exportConversation;root.querySelector('#smImport').onclick=importConversation;renderThread();}
async function renderThread(){if(!currentThread)return;currentThread.innerHTML='';for(const m of loadMessages()){const row=document.createElement('div');row.className='bubble-row '+(m.mine?'me':'them');const bubble=document.createElement('div');bubble.className='msg-bubble';if(m.text){const text=document.createElement('div');text.textContent=m.text;bubble.append(text)}if(m.attachmentId){const rec=await getBlob(m.attachmentId).catch(()=>null);if(rec){const url=URL.createObjectURL(rec.blob);let media;if(rec.type.startsWith('image/')){media=document.createElement('img');media.style.cssText='max-width:230px;max-height:260px;border-radius:12px;display:block;margin-top:6px';media.src=url}else if(rec.type.startsWith('video/')){media=document.createElement('video');media.controls=true;media.playsInline=true;media.style.cssText='max-width:240px;max-height:300px;border-radius:12px;display:block;margin-top:6px';media.src=url}else if(rec.type.startsWith('audio/')){media=document.createElement('audio');media.controls=true;media.src=url}else{media=document.createElement('a');media.href=url;media.download=rec.name;media.textContent='📎 '+rec.name;media.style.color=m.mine?'#fff':'#06c'}bubble.append(media)}}const tm=document.createElement('div');tm.className='msg-time';tm.textContent=new Date(m.time).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});bubble.append(tm);row.append(bubble);currentThread.append(row)}currentThread.scrollTop=currentThread.scrollHeight}
function sendText(text){addMessage({mine:true,text});if(RTC.dc&&RTC.dc.readyState==='open')RTC.dc.send(JSON.stringify({type:'text',text,time:Date.now()}));else toast('Saved here — connect another phone to send live')}
async function sendFile(file){if(file.size>25*1024*1024){toast('Keep attachments under 25 MB');return}const id=await putBlob(file,file.name,file.type);addMessage({mine:true,attachmentId:id,attachmentName:file.name,attachmentType:file.type});if(!RTC.dc||RTC.dc.readyState!=='open'){toast('Saved here — connect another phone to send');return}const data=new Uint8Array(await file.arrayBuffer());const transferId=crypto.randomUUID();RTC.dc.send(JSON.stringify({type:'file-start',id:transferId,name:file.name,mime:file.type,size:data.length}));const chunk=12000;for(let i=0;i<data.length;i+=chunk){while(RTC.dc.bufferedAmount>1024*1024)await new Promise(r=>setTimeout(r,40));RTC.dc.send(JSON.stringify({type:'file-chunk',id:transferId,data:bytesToB64(data.subarray(i,i+chunk))}))}RTC.dc.send(JSON.stringify({type:'file-end',id:transferId}))}
function bytesToB64(u){let s='';const step=8192;for(let i=0;i<u.length;i+=step)s+=String.fromCharCode(...u.subarray(i,i+step));return btoa(s)}function b64ToBytes(s){const b=atob(s),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return u}
const incoming=new Map();
function handleData(ev){if(typeof ev.data!=='string')return;let m;try{m=JSON.parse(ev.data)}catch{return}if(m.type==='text'){addMessage({mine:false,text:m.text,time:m.time||Date.now()})}else if(m.type==='file-start'){incoming.set(m.id,{name:m.name,mime:m.mime,chunks:[],size:m.size})}else if(m.type==='file-chunk'){const r=incoming.get(m.id);if(r)r.chunks.push(b64ToBytes(m.data))}else if(m.type==='file-end'){finishIncoming(m.id)}}
async function finishIncoming(id){const r=incoming.get(id);if(!r)return;incoming.delete(id);let size=0;r.chunks.forEach(c=>size+=c.length);const all=new Uint8Array(size);let o=0;r.chunks.forEach(c=>{all.set(c,o);o+=c.length});const blob=new Blob([all],{type:r.mime});const fid=await putBlob(blob,r.name,r.mime);addMessage({mine:false,attachmentId:fid,attachmentName:r.name,attachmentType:r.mime})}

function waitIce(pc){return new Promise(res=>{if(pc.iceGatheringState==='complete')return res();const f=()=>{if(pc.iceGatheringState==='complete'){pc.removeEventListener('icegatheringstatechange',f);res()}};pc.addEventListener('icegatheringstatechange',f);setTimeout(res,5000)})}
function makePC(){if(RTC.pc)try{RTC.pc.close()}catch{}const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});RTC.pc=pc;RTC.connected=false;RTC.remoteStream=new MediaStream();pc.addTransceiver('audio',{direction:'sendrecv'});pc.addTransceiver('video',{direction:'sendrecv'});pc.ontrack=e=>{RTC.remoteStream.addTrack(e.track);showRemoteMedia()};pc.onconnectionstatechange=()=>{RTC.connected=pc.connectionState==='connected';if(RTC.connected)toast('Phones connected');if(['failed','closed','disconnected'].includes(pc.connectionState))RTC.connected=false};return pc}
function setupDC(dc){RTC.dc=dc;dc.onopen=()=>toast('Secret Message connected');dc.onmessage=handleData;dc.onclose=()=>toast('Secret Message disconnected')}
function codeFromDesc(desc){return btoa(unescape(encodeURIComponent(JSON.stringify(desc))))}function descFromCode(code){return JSON.parse(decodeURIComponent(escape(atob(code.trim()))))}
function openConnect(){const overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;background:#000b;z-index:200;display:grid;place-items:center;padding:18px';const c=document.createElement('div');c.className='ios-card';c.style.cssText+=';width:min(100%,520px);max-height:90vh;overflow:auto';c.innerHTML='<h2 style="margin-top:0">Connect another phone</h2><div class="privacy-note">Phone A creates an invite. Phone B pastes it and makes an answer. Phone A pastes the answer. No account is required.</div>';
 const role=document.createElement('div');role.className='transfer-row';const host=document.createElement('button');host.className='transfer-btn';host.textContent='Phone A: Create Invite';const join=document.createElement('button');join.className='transfer-btn';join.textContent='Phone B: Join Invite';role.append(host,join);const area=document.createElement('textarea');area.className='field';area.style.cssText='width:100%;height:140px;margin-top:12px;font-size:11px';area.placeholder='Connection code appears here / paste code here';const action=document.createElement('button');action.className='primary';action.style.marginTop='9px';action.textContent='Use Code';action.disabled=true;const close=document.createElement('button');close.className='transfer-btn';close.style.cssText='width:100%;margin-top:9px';close.textContent='Close';close.onclick=()=>overlay.remove();c.append(role,area,action,close);overlay.append(c);document.body.append(overlay);
 host.onclick=async()=>{const pc=makePC();setupDC(pc.createDataChannel('secret-message',{ordered:true}));const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);area.value=codeFromDesc(pc.localDescription);action.disabled=false;action.textContent='Phone A: Paste Phone B Answer, then tap here';action.onclick=async()=>{try{await pc.setRemoteDescription(descFromCode(area.value));toast('Answer accepted — connecting…');overlay.remove()}catch{toast('That answer code did not work')}}};
 join.onclick=()=>{const pc=makePC();pc.ondatachannel=e=>setupDC(e.channel);area.value='';area.placeholder='Paste Phone A invite code here';action.disabled=false;action.textContent='Phone B: Make Answer';action.onclick=async()=>{try{await pc.setRemoteDescription(descFromCode(area.value));const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await waitIce(pc);area.value=codeFromDesc(pc.localDescription);area.select();action.textContent='Answer ready — copy this back to Phone A';action.disabled=true}catch{toast('That invite code did not work')}}};}
async function startCall(video){if(!RTC.pc||!RTC.connected){toast('Connect the two phones first');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true,video});RTC.localStream=stream;const senders=RTC.pc.getSenders();const audio=stream.getAudioTracks()[0],vid=stream.getVideoTracks()[0];const as=senders.find(s=>s.track?.kind==='audio'||s.track===null);const vs=senders.filter(s=>s!==as).find(s=>s.track?.kind==='video'||s.track===null);if(as&&audio)await as.replaceTrack(audio);if(vs)await vs.replaceTrack(vid||null);showLocalMedia(video);toast(video?'Video call started':'Call started')}catch{toast('Camera/microphone permission is needed')}}
function showRemoteMedia(){let box=document.getElementById('smRemoteMedia');if(!box){box=document.createElement('div');box.id='smRemoteMedia';box.style.cssText='position:fixed;inset:0;background:#000;z-index:300;display:grid;place-items:center';const v=document.createElement('video');v.id='smRemoteVideo';v.autoplay=true;v.playsInline=true;v.style.cssText='width:100%;height:100%;object-fit:cover';const end=document.createElement('button');end.textContent='End';end.style.cssText='position:absolute;bottom:40px;width:72px;height:72px;border-radius:50%;background:#e33;color:white;font-weight:800';end.onclick=endCall;box.append(v,end);document.body.append(box)}const v=box.querySelector('video');v.srcObject=RTC.remoteStream}
function showLocalMedia(video){showRemoteMedia();if(!video)return;let v=document.getElementById('smLocalVideo');if(!v){v=document.createElement('video');v.id='smLocalVideo';v.autoplay=true;v.muted=true;v.playsInline=true;v.style.cssText='position:absolute;right:14px;top:54px;width:100px;height:145px;object-fit:cover;border-radius:14px;border:2px solid white;z-index:2';document.getElementById('smRemoteMedia').append(v)}v.srcObject=RTC.localStream}
function endCall(){if(RTC.localStream)RTC.localStream.getTracks().forEach(t=>t.stop());RTC.localStream=null;const box=document.getElementById('smRemoteMedia');if(box)box.remove();if(RTC.pc)RTC.pc.getSenders().forEach(s=>{if(s.track)s.replaceTrack(null).catch(()=>{})})}

async function deriveKey(pass,salt){const base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function exportConversation(){const pass=prompt('Make a passphrase for this Secret Message file:');if(!pass)return;const payload={version:1,messages:loadMessages()};const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(pass,salt);const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(payload))));const obj={salt:bytesToB64(salt),iv:bytesToB64(iv),data:bytesToB64(ct)};const blob=new Blob([JSON.stringify(obj)],{type:'application/octet-stream'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Secret-Message.secretmsg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importConversation(){const inp=document.createElement('input');inp.type='file';inp.accept='.secretmsg,application/octet-stream';inp.onchange=async()=>{const f=inp.files&&inp.files[0];if(!f)return;const pass=prompt('Enter the passphrase for this Secret Message file:');if(!pass)return;try{const obj=JSON.parse(await f.text()),salt=b64ToBytes(obj.salt),iv=b64ToBytes(obj.iv),data=b64ToBytes(obj.data),key=await deriveKey(pass,salt);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,data);const payload=JSON.parse(dec.decode(plain));if(!Array.isArray(payload.messages))throw 0;saveMessages(payload.messages);toast('Secret Messages imported');renderThread()}catch{toast('Could not unlock that Secret Message file')}};inp.click()}
})();