(()=>{
const pages=document.getElementById('phonePages'),dock=document.getElementById('phoneDock'),app=document.getElementById('app'),home=document.getElementById('home'),toastEl=document.getElementById('toast');
if(!pages||!dock||!app||!home)return;
const fixedLinks={
 'Ninja Y':'https://ninja-y-game.cwhit.chatgpt.site',
 "Malachi's Mowing":'https://malachis-mowing-fort-scott.cwhit.chatgpt.site',
 'Brainrot Movie Maker':'https://brainrot-movie-maker.cwhit.chatgpt.site',
 'Ava':'https://chatgpt.com/'
};
function show(el){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
function toast(m){if(!toastEl)return;toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1300)}
function shell(title,back){app.innerHTML='';const p=document.createElement('div');p.className='page settings-page';const h=document.createElement('div');h.className='head settings-head';const b=document.createElement('button');b.className='back';b.textContent=back?'‹ Settings':'‹ Home';b.onclick=back||(()=>show(home));const t=document.createElement('h2');t.textContent=title;h.append(b,t);p.append(h);app.append(p);show(app);return p}
function section(title){const wrap=document.createElement('div');wrap.className='settings-section';const label=document.createElement('div');label.className='settings-section-title';label.textContent=title;const list=document.createElement('div');list.className='settings-list';wrap.append(label,list);return {wrap,list}}
function row(icon,title,detail,fn){const b=document.createElement('button');b.className='settings-row';b.innerHTML='<span class="settings-row-icon"></span><span class="settings-row-text"><strong></strong><small></small></span><span class="settings-chevron">›</span>';b.querySelector('.settings-row-icon').textContent=icon;b.querySelector('strong').textContent=title;b.querySelector('small').textContent=detail||'';b.onclick=fn;return b}
function openSettings(){
 const p=shell('Settings');p.classList.add('project-link-settings');
 const profile=document.createElement('div');profile.className='settings-profile';profile.innerHTML='<div class="settings-profile-icon">⌗</div><div><strong>Calculator</strong><span>Private phone settings</span></div>';p.append(profile);
 const security=section('SECURITY');security.list.append(row('🔒','Passcode','Change Calculator unlock code',openPasscode));p.append(security.wrap);
 const appearance=section('APPEARANCE');appearance.list.append(row('🖼️','Wallpaper','Change the private Home Screen background',openWallpaper));p.append(appearance.wrap);
 const apps=section('APPS');apps.list.append(row('▦','Apps & Links','Review connected games and websites',openApps));p.append(apps.wrap);
 const comms=section('PHONE & MESSAGING');comms.list.append(row('☎','My Calculator Number',window.CalculatorPhone?.number?.()||'Open Phone once to create a number',openNumberInfo));comms.list.append(row('●','Calling & Messages','Ringtone and connection information',openCalling));p.append(comms.wrap);
 const storage=section('STORAGE');storage.list.append(row('📷','Private Photos','Photos stay in Calculator storage',()=>window.CalculatorPrivatePhotos?.openGallery?.()));storage.list.append(row('📁','Private Files','Files stay in Calculator storage',openStorageInfo));p.append(storage.wrap);
 const about=section('ABOUT');about.list.append(row('ⓘ','Calculator Version','v42',()=>toast('Calculator v42')));p.append(about.wrap);
}
function inputRow(label,type='password'){const wrap=document.createElement('label');wrap.className='settings-input-row';const span=document.createElement('span');span.textContent=label;const i=document.createElement('input');i.type=type;i.inputMode='numeric';i.autocomplete='off';wrap.append(span,i);return {wrap,input:i}}
function openPasscode(){const p=shell('Passcode',openSettings);const card=document.createElement('div');card.className='settings-form-card';const current=inputRow('Current Passcode'),next=inputRow('New Passcode'),confirm=inputRow('Confirm New Passcode');const save=document.createElement('button');save.className='primary settings-save';save.textContent='Change Passcode';save.onclick=()=>{const old=localStorage.getItem('main-code')||'5963';if(current.input.value!==old)return toast('Current passcode is wrong');if(!/^\d{4,10}$/.test(next.input.value))return toast('Use 4–10 numbers');if(next.input.value!==confirm.input.value)return toast('Passcodes do not match');localStorage.setItem('main-code',next.input.value);toast('Passcode changed');setTimeout(openSettings,500)};card.append(current.wrap,next.wrap,confirm.wrap,save);const note=document.createElement('div');note.className='settings-note';note.textContent='The new code works immediately the next time Calculator is locked.';p.append(card,note)}
function openWallpaper(){const p=shell('Wallpaper',openSettings);const panel=window.CalculatorPersonalize?.panel?.();if(panel){p.append(panel);return}const card=document.createElement('div');card.className='settings-form-card';const title=document.createElement('strong');title.textContent='Private Home Screen Wallpaper';const input=document.createElement('input');input.type='file';input.accept='image/*';input.hidden=true;const choose=document.createElement('button');choose.className='primary';choose.textContent='Choose Photo';choose.onclick=()=>input.click();const reset=document.createElement('button');reset.className='settings-secondary';reset.textContent='Use Default';reset.onclick=()=>{localStorage.removeItem('phone-wallpaper');applyWallpaper();toast('Default wallpaper restored')};input.onchange=()=>{const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{localStorage.setItem('phone-wallpaper',String(r.result));applyWallpaper();toast('Wallpaper changed')}catch{toast('That photo is too large')}};r.readAsDataURL(f)};card.append(title,choose,reset,input);p.append(card)}
function applyWallpaper(){const shell=document.querySelector('#home .phone-shell');if(!shell)return;const w=localStorage.getItem('phone-wallpaper');if(w){shell.style.backgroundImage=`linear-gradient(rgba(0,0,0,.08),rgba(0,0,0,.08)),url("${w}")`;shell.style.backgroundSize='cover';shell.style.backgroundPosition='center'}else{shell.style.backgroundImage=''}}
function openApps(){const p=shell('Apps & Links',openSettings);const s=section('CONNECTED');Object.entries(fixedLinks).forEach(([name,url])=>s.list.append(row(name==='Ava'?'✦':'↗',name,'Connected',()=>location.href=url)));for(const [name,id] of [['Ninja','ninja'],['X','x'],['Deep Scope','deepscope']]){const url=localStorage.getItem('project-url-'+id)||'';s.list.append(row('↗',name,url?'Connected':'Not connected',()=>{if(url)location.href=url;else toast(name+' link is not connected')}))}p.append(s.wrap)}
function openNumberInfo(){const p=shell('My Calculator Number',openSettings);const card=document.createElement('div');card.className='settings-info-card';const num=window.CalculatorPhone?.number?.()||'Not ready yet';card.innerHTML='<span>Calculator Number</span><strong></strong><small>This number is used only inside Calculator calling and messaging.</small>';card.querySelector('strong').textContent=num;p.append(card)}
function openCalling(){const p=shell('Calling & Messages',openSettings);const card=document.createElement('div');card.className='settings-info-card';card.innerHTML='<strong>Incoming Calls</strong><small>Calculator uses its private ringtone while the app is active. Background lock-screen ringing requires push notifications and is a separate feature.</small>';p.append(card)}
function openStorageInfo(){const p=shell('Private Files',openSettings);const card=document.createElement('div');card.className='settings-info-card';card.innerHTML='<strong>Calculator Storage</strong><small>Files and private photos are stored separately inside this Calculator installation on this device.</small>';p.append(card)}
function intercept(e){const b=e.target.closest?.('.phone-app');if(b?.querySelector('.phone-label')?.textContent?.trim()!=='Settings')return;e.preventDefault();e.stopImmediatePropagation();openSettings()}
pages.addEventListener('click',intercept,true);dock.addEventListener('click',intercept,true);applyWallpaper();window.CalculatorSettings={open:openSettings};
})();
